# This workflow makes sure that a pull request does not make any incompatible changes
# to the public API of Gson
name: Check API compatibility

on: pull_request

jobs:
  check-api-compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4

      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9  # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Check API compatibility
        id: check-compatibility
        run: |
          mvn --batch-mode --fail-at-end --no-transfer-progress package japicmp:cmp -DskipTests

      - name: Upload API differences artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.3.3
        # Run on workflow success (in that case differences report might include added methods and classes)
        # or when API compatibility check failed
        if: success() || ( failure() && steps.check-compatibility.outcome == 'failure' )
        with:
          name: api-differences
          path: |
            **/japicmp/default-cli.html
            **/japicmp/default-cli.diff
          # Plugin should always have created report files (though they might be empty)
          if-no-files-found: error
